server {
    listen 443 ssl;
    ssl_certificate     /etc/nginx/certs/tls.crt;
    ssl_certificate_key /etc/nginx/certs/tls.key;
    client_max_body_size 4m;
    location / {
        proxy_pass http://kms:9090;
        proxy_set_header Host $host;
    }
}
